### ISSUE TITLE
For all the nodes in GRID5000 is not possible to create a dataframe

### ISSUE THREAD

**Issue by Brandonage** [Brandonage/execo-utilities-g5k#1]
It would be interesting to create a pandas dataframe of all the nodes in g5k. 

df_all_nodes = general_util.build_dataframe_of_nodes( get_g5k_hosts())

This raises an exception

```
Traceback (most recent call last):
  File "/Users/alvarobrandon/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-70-ea6ebc2ef6e5>", line 1, in <module>
    df_all_hosts = build_dataframe_of_nodes(all_hosts)
  File "/Users/alvarobrandon/PycharmProjects/execo_utilities_g5k/general_util.py", line 63, in build_dataframe_of_nodes
    values = [get_resource(node_dict,resource) for node_dict in list_of_nodes_dict] ## Get a list of the values for that resource
  File "/Users/alvarobrandon/PycharmProjects/execo_utilities_g5k/general_util.py", line 36, in get_resource
    return list_of_results[0].value ##return the single value
IndexError: list index out of range
```

**Comment by Brandonage** [comment]
This has been implemented and is working fine
